#!/usr/bin/env python3
"""Build data/grids.json, the catalogue of available grids, from data/*.json.

The web app can't list the data/ directory over HTTP (static hosting has no
directory listing), so it fetches this manifest instead. Re-run this script
whenever grid or puzzle files are added to or removed from data/.

Usage: python3 util/build_catalogue.py
(No arguments; runs from anywhere, writes <repo>/data/grids.json.)

Grid files are recognized by having "gridId", "vertices" and "faces"
properties. Each is paired with its "<stem>-puzzles.json" file (if any) to
count available puzzles. Entries are sorted by size (edges, then faces) as
a first approximation of difficulty; the app presents them in this order,
which will eventually also serve as the player's progression order.

Note that the "file" property (the filename stem used to fetch
data/<file>.json) can differ from the grid's internal "gridId" —
e.g. cube.json has gridId "C".
"""
import json
import sys
from pathlib import Path

import json_format

DATA_DIR = Path(__file__).resolve().parent.parent / "data"
CATALOGUE_PATH = DATA_DIR / "grids.json"


def count_edges(faces):
    """Each edge is shared by exactly two faces on a closed mesh, so the
    edge count is half the total number of face sides."""
    total_sides = sum(len(face) for face in faces)
    if total_sides % 2 != 0:
        raise ValueError("Total face sides is odd; mesh is not closed.")
    return total_sides // 2


def build_entry(grid_path):
    """Build one catalogue entry from a grid file, or return None if the
    file isn't a grid (e.g. a puzzles file or this catalogue itself)."""
    data = json.load(open(grid_path))
    if not all(prop in data for prop in ("gridId", "vertices", "faces")):
        return None

    puzzles_path = grid_path.with_name(grid_path.stem + "-puzzles.json")
    num_puzzles = 0
    if puzzles_path.exists():
        puzzles_data = json.load(open(puzzles_path))
        if puzzles_data.get("gridId") != data["gridId"]:
            print(f"Warning: {puzzles_path.name} has gridId "
                  f"'{puzzles_data.get('gridId')}' but {grid_path.name} has "
                  f"'{data['gridId']}'; skipping its puzzles.", file=sys.stderr)
        else:
            num_puzzles = len(puzzles_data.get("puzzles", []))

    return {
        "file": grid_path.stem,   # fetch as data/<file>.json
        "gridId": data["gridId"],
        "gridName": data.get("gridName", grid_path.stem),
        "categories": data.get("categories", []),
        "faces": len(data["faces"]),
        "edges": count_edges(data["faces"]),
        "vertices": len(data["vertices"]),
        "numPuzzles": num_puzzles,
    }


def main():
    entries = []
    for grid_path in sorted(DATA_DIR.glob("*.json")):
        if grid_path.name == CATALOGUE_PATH.name or grid_path.stem.endswith("-puzzles"):
            continue
        entry = build_entry(grid_path)
        if entry is None:
            print(f"Skipping {grid_path.name}: not a grid file.", file=sys.stderr)
            continue
        entries.append(entry)

    # Sort by size as a rough difficulty progression. The sort must stay
    # deterministic, since regeneration overwrites any manual reordering.
    entries.sort(key=lambda e: (e["edges"], e["faces"], e["gridId"]))

    catalogue = {
        "_comment": "Generated by util/build_catalogue.py -- do not edit by hand.",
        "grids": entries,
    }
    with open(CATALOGUE_PATH, "w") as f:
        json_format.write_json(catalogue, f)
    print(f"Wrote {CATALOGUE_PATH} with {len(entries)} grids:")
    for e in entries:
        print(f"  {e['file']:6s} {e['gridName']:24s} "
              f"F={e['faces']:3d} E={e['edges']:3d} puzzles={e['numPuzzles']}")


if __name__ == "__main__":
    main()
