#!/usr/bin/env python3
"""Readable JSON for the data files.

Both extremes are hard to read. Minified, a grid is one 1000-character line
(genUniformPolyh used to write them that way). Fully indented, every coordinate
and every clue gets a line of its own, so a puzzle file ran to 491 lines to say
very little -- json.dump(..., indent=3) does that.

The rule here is the middle ground: a list of plain values stays on ONE line,
and anything containing a list or a dict is expanded. That gives one line per
vertex, per face, per clue array, which is the level a human wants to read:

    {
      "gridId": "C",
      "categories": ["Platonic solid", "parallelohedron", "zonohedron"],
      "vertices": [
        [-0.577350269, -0.577350269, -0.577350269],
        ...

Run it over files to reformat them in place:

    python3 util/json_format.py data/*.json
"""

import json
import shlex
import sys
from pathlib import Path

# Arguments that cannot change what lands in the file, and so are left out of the
# "source" line: where to write it, and how much to say while doing it.
NON_CONTENT_ARGUMENTS = ('--out=', '--quiet', '-q', '--verbose', '-v')


def source_line(arguments=None):
    """The "source" property: the command that reproduces this file.

    Built from sys.argv by default, which is the point -- a hand-written source line
    has to be remembered every time an option is added, and genGoldberg's quietly
    omitted the grid id and name when those were passed on the command line, so its
    files claimed to come from a command that would have named them differently.

    Every argument that affects the CONTENTS is kept, since the promise this makes is
    that pasting the line back reproduces the file (see docs/json-format.md).
    Destination and verbosity flags are dropped: --out= says where the bytes went, not
    what they are, and a file naming its own path is no help to anyone.

    @param arguments: pass explicitly where argv does not describe this one file --
        a script whose --all mode writes several should pass the arguments that make
        just this one, so the line reproduces the file it sits in rather than its
        siblings too
    @returns e.g. 'Generated by util/genPrism.py --anti 6.'
    """
    argv = sys.argv[1:] if arguments is None else [str(a) for a in arguments]
    kept = [a for a in argv if not a.startswith(NON_CONTENT_ARGUMENTS)]
    # shlex.quote so a name with spaces stays one argument when pasted back.
    spelled = ' '.join(shlex.quote(a) for a in kept)
    # By path from the repo root, which is how the docs invoke these scripts.
    script = f'util/{Path(sys.argv[0]).name}'
    return f'Generated by {script}{" " + spelled if spelled else ""}.'


def is_leaf_list(value):
    """A list with nothing nested in it, so it can sit on one line."""
    return (isinstance(value, list)
            and not any(isinstance(item, (list, dict)) for item in value))


def format_json(value, indent=2, level=0):
    """
    Serializes value as JSON, keeping leaf lists on one line.

    @param value: anything json.dumps accepts
    @param indent: spaces per level
    @param level: current depth, for the recursive calls
    @returns: the JSON text, with no trailing newline
    """
    pad = ' ' * (indent * level)
    inner_pad = ' ' * (indent * (level + 1))

    if isinstance(value, dict):
        if not value:
            return '{}'
        lines = [f'{inner_pad}{json.dumps(str(key))}: '
                 f'{format_json(item, indent, level + 1)}'
                 for (key, item) in value.items()]
        return '{\n' + ',\n'.join(lines) + f'\n{pad}}}'

    if isinstance(value, list):
        if not value:
            return '[]'
        if is_leaf_list(value):
            # The whole point: coordinates, face indices and clue lists read as
            # one line each, not as a column of numbers.
            return json.dumps(value)
        lines = [f'{inner_pad}{format_json(item, indent, level + 1)}'
                 for item in value]
        return '[\n' + ',\n'.join(lines) + f'\n{pad}]'

    # Scalars: let json handle the escaping and the float repr (which is the
    # shortest string that round-trips, so rounded coordinates stay as written).
    return json.dumps(value)


def write_json(value, file, indent=2):
    """Writes value to an open file as formatted JSON, with a trailing newline."""
    file.write(format_json(value, indent))
    file.write('\n')


def reformat_file(path, indent=2):
    """
    Rewrites one JSON file in this format. Idempotent, and it round-trips: the
    parsed data is compared before and after, so a bug here can't silently
    corrupt a data file.
    """
    with open(path) as f:
        original = json.load(f)
    text = format_json(original, indent) + '\n'
    if json.loads(text) != original:
        raise AssertionError(f'reformatting {path} would change its data')
    with open(path, 'w') as f:
        f.write(text)


def main():
    paths = sys.argv[1:]
    if not paths:
        print(__doc__)
        print('Usage: python3 util/json_format.py <file.json> ...')
        return 1
    for path in paths:
        reformat_file(path)
        print(f'formatted {path}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
